lib/chess_crunch_web/router.ex
defmodule ChessCrunchWeb.Router do
  use ChessCrunchWeb, :router

  import ChessCrunchWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ChessCrunchWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  scope "/", ChessCrunchWeb do
    pipe_through :browser
  end

  ## Authentication routes

  scope "/", ChessCrunchWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ChessCrunchWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", Redirector, to: "/cycles"
    resources "/cycles", CycleController, only: [:index, :create, :new, :show, :delete]
    live "/start_cycle/:id", CycleLive
    resources "/sets", SetController, only: [:index, :new, :create, :show, :delete]
    resources "/positions", PositionController, only: [:new, :create, :delete]
    live "/positions/:id/edit", EditPositionLive
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ChessCrunchWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChessCrunchWeb.Telemetry
    end
  end
end

lib/chess_crunch_web/controllers/user_registration_controller.ex
defmodule ChessCrunchWeb.UserRegistrationController do
  use ChessCrunchWeb, :controller

  alias ChessCrunch.Accounts
  alias ChessCrunch.Accounts.User
  alias ChessCrunchWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/chess_crunch_web/views/user_registration_view.ex
defmodule ChessCrunchWeb.UserRegistrationView do
  use ChessCrunchWeb, :view
end

lib/chess_crunch_web/templates/user_registration/new.html.eex
<div class="flex justify-center mt-20">
  <div class="rounded bg-gray-300 px-10 py-5 max-w-xs">
    <h1 class="text-center text-xl mb-4">Register</h1>

    <%= form_for @changeset, Routes.user_registration_path(@conn, :create), [class: "flex flex-col m-2"], fn f -> %>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p class="mb-0">Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <div class="flex flex-col space-y-0.5">
        <%= email_input f, :email, required: true, placeholder: "Email", class: "p-1 border rounded" %>
        <%= error_tag f, :email %>
        <%= password_input f, :password, required: true, placeholder: "Password", class: "p-1 border rounded" %>
        <%= error_tag f, :password %>
      </div>

      <div class="flex justify-center mt-4">
        <div class="py-1 w-3/4 rounded text-center bg-green-500">
          <%= submit "Register" %>
        </div>
      </div>
    <% end %>

    <p class="mt-4 text-sm text-center">
      <%= link "Log In", to: Routes.user_session_path(@conn, :new) %> |
      <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
    </p>
  </div>
</div>