lib/chess_crunch_web/router.ex
defmodule ChessCrunchWeb.Router do
  use ChessCrunchWeb, :router

  import ChessCrunchWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ChessCrunchWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  scope "/", ChessCrunchWeb do
    pipe_through :browser
  end

  ## Authentication routes

  scope "/", ChessCrunchWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ChessCrunchWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", Redirector, to: "/cycles"
    resources "/cycles", CycleController, only: [:index, :create, :new, :show, :delete]
    live "/start_cycle/:id", CycleLive
    resources "/sets", SetController, only: [:index, :new, :create, :show, :delete]
    resources "/positions", PositionController, only: [:new, :create, :delete]
    live "/positions/:id/edit", EditPositionLive
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ChessCrunchWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChessCrunchWeb.Telemetry
    end
  end
end

lib/chess_crunch/sets.ex
defmodule ChessCrunch.Sets do
  @moduledoc """
  The Sets context.
  """

  import Ecto.Query, warn: false
  alias ChessCrunch.Repo
  alias ChessCrunch.Sets.{Position, Set}

  @doc """
  Returns the list of sets.

  ## Examples

      iex> list_sets()
      [%Set{}, ...]

  """
  def list_sets(user) do
    Set
    |> where(user_id: ^user.id)
    |> Repo.all()
  end

  def find_sets_by_ids(ids) do
    Set
    |> where([set], set.id in ^ids)
    |> Repo.all()
  end

  @doc """
  Gets a single set.

  Raises `Ecto.NoResultsError` if the Set does not exist.

  ## Examples

      iex> get_set!(123)
      %Set{}

      iex> get_set!(456)
      ** (Ecto.NoResultsError)

  """
  def get_set!(id) do
    from(s in Set,
      left_join: p in assoc(s, :positions),
      order_by: p.inserted_at,
      preload: [positions: p]
    )
    |> Repo.get!(id)
  end

  @doc """
  Creates a set.

  ## Examples

      iex> create_set(%{field: value})
      {:ok, %Set{}}

      iex> create_set(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_set(attrs \\ %{}) do
    %Set{}
    |> Set.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a set.

  ## Examples

      iex> update_set(set, %{field: new_value})
      {:ok, %Set{}}

      iex> update_set(set, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_set(%Set{} = set, attrs) do
    set
    |> Set.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a set.

  ## Examples

      iex> delete_set(set)
      {:ok, %Set{}}

      iex> delete_set(set)
      {:error, %Ecto.Changeset{}}

  """
  def delete_set(%Set{} = set) do
    Repo.delete(set)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking set changes.

  ## Examples

      iex> change_set(set)
      %Ecto.Changeset{data: %Set{}}

  """
  def change_set(%Set{} = set, attrs \\ %{}) do
    Set.changeset(set, attrs)
  end

  def change_position(%Position{} = position, attrs \\ %{}) do
    Position.changeset(position, attrs)
  end

  def create_position(attrs \\ %{}) do
    %Position{}
    |> Position.changeset(attrs)
    |> Repo.insert()
  end

  def get_position!(id), do: Repo.get!(Position, id)

  def update_position(%Position{} = position, attrs) do
    position
    |> Position.changeset(attrs)
    |> Repo.update!()
  end

  def delete_position!(position), do: Repo.delete!(position)

  def format_to_play(%{to_play: "w"}, caps: false), do: "white"
  def format_to_play(_, caps: false), do: "black"
  def format_to_play(%{to_play: "w"}), do: "White"
  def format_to_play(_), do: "Black"

  def needs_solutions?(set) do
    Repo.preload(set, :positions).positions
    |> Enum.any?(&is_nil(&1.solution_fen))
  end

  def load_parent_cycles(position) do
    Repo.preload(position, set: [cycles: [:rounds, :sets]])
  end
end

lib/chess_crunch/sets/position.ex
defmodule ChessCrunch.Sets.Position do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}

  schema "positions" do
    field :fen, :string
    field :solution_moves, :string
    field :solution_fen, :string
    field :to_play, :string
    field :name, :string
    belongs_to(:set, ChessCrunch.Sets.Set)

    timestamps()
  end

  @doc false
  def changeset(position, attrs) do
    position
    |> cast(attrs, [:fen, :solution_moves, :solution_fen, :to_play, :set_id, :name])
    |> validate_required([:to_play, :set_id, :name])
  end
end

lib/chess_crunch/sets/set.ex
defmodule ChessCrunch.Sets.Set do
  use Ecto.Schema
  import Ecto.Changeset

  schema "sets" do
    field :name, :string

    has_many :positions, ChessCrunch.Sets.Position
    many_to_many :cycles, ChessCrunch.Cycles.Cycle, join_through: "cycles_sets"
    belongs_to :user, ChessCrunch.Accounts.User, type: :binary_id

    timestamps()
  end

  @doc false
  def changeset(set, attrs) do
    set
    |> cast(attrs, [:name, :user_id])
    |> validate_required([:name, :user_id])
  end
end

lib/chess_crunch_web/controllers/set_controller.ex
defmodule ChessCrunchWeb.SetController do
  use ChessCrunchWeb, :controller

  alias ChessCrunch.Sets
  alias ChessCrunch.Sets.Set

  def index(conn, _params) do
    sets = Sets.list_sets(current_user(conn))
    render(conn, "index.html", sets: sets)
  end

  def new(conn, _params) do
    changeset = Sets.change_set(%Set{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"set" => set_params}) do
    set_params
    |> Map.put("user_id", current_user(conn).id)
    |> Sets.create_set()
    |> case do
      {:ok, set} ->
        conn
        |> put_flash(:info, "Set created successfully.")
        |> redirect(to: Routes.set_path(conn, :show, set))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    set = Sets.get_set!(id)
    render(conn, "show.html", set: set)
  end

  def delete(conn, %{"id" => id}) do
    set = Sets.get_set!(id)
    {:ok, _set} = Sets.delete_set(set)

    conn
    |> put_flash(:info, "Set deleted successfully.")
    |> redirect(to: Routes.set_path(conn, :index))
  end

  defp current_user(conn) do
    conn.assigns[:current_user]
  end
end

lib/chess_crunch_web/views/set_view.ex
defmodule ChessCrunchWeb.SetView do
  use ChessCrunchWeb, :view

  def solution_status(nil), do: "Needs Solution"
  def solution_status(_), do: nil
end

lib/chess_crunch_web/templates/set/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="flex flex-col space-y-0.5">
    <%= text_input f, :name, placeholder: "Name", class: "p-1 border rounded" %>
    <%= error_tag f, :name %>
  </div>

  <div class="text-center mt-5">
    <%= submit "Save", class: "btn bg-blue-400 px-5" %>
  </div>
<% end %>

lib/chess_crunch_web/templates/set/index.html.eex
<%= if Enum.empty?(@sets) do %>
  <div class="text-center mt-24">
    <div>You have not created any sets.</div>
  </div>
  <div class="my-6 text-center">
    <%= link "Create new position set", to: Routes.set_path(@conn, :new), class: "btn-blue p-2" %>
  </div>
<% else %>
  <div class="my-6 text-center">
    <%= link "Create new position set", to: Routes.set_path(@conn, :new), class: "btn-blue p-2" %>
  </div>

  <ul class="m-3 px-3 border rounded">
    <%= for set <- @sets do %>
      <li class="border-b last:border-b-0 py-1">
        <%= link to: Routes.set_path(@conn, :show, set), class: "block" do %>
          <%= set.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

lib/chess_crunch_web/templates/set/new.html.eex
<div class="mx-4">
  <h1 class="text-2xl my-4">Create a new set</h1>

  <%= render "form.html", Map.put(assigns, :action, Routes.set_path(@conn, :create)) %>

  <%# <span><%= link "Back", to: Routes.set_path(@conn, :index) %1></span> %>
</div>

lib/chess_crunch_web/templates/set/show.html.eex
<section class="mt-5 px-8 pb-3">
  <h1 class="my-3 text-center text-3xl">
    <%= @set.name %>
  </h1>

  <div class="mt-8 mb-7 flex flex-col text-center">
    <div class="mb-8">
      <%= link "Add Position", to: Routes.position_path(@conn, :new, set_id: @set.id), class: "btn-green" %>
    </div>
    <div>
      <%= link "Delete Set", to: Routes.set_path(@conn, :delete, @set), method: :delete, class: "btn-red p-1 px-2" %>
    </div>
  </div>
</section>

<div class="mx-4">
  <strong>
    <%= length(@set.positions) %> positions
  </strong>
</div>

<ul class="m-3 px-3 border rounded">
  <%= for position <- @set.positions do %>
    <li class="border-b last:border-b-0 py-1">
      <%= link to: Routes.live_path(@conn, ChessCrunchWeb.EditPositionLive, position), class: "flex justify-between" do %>
        <div><%= position.name %></div>
        <div class="text-red-500"><%= solution_status(position.solution_fen) %></div>
      <% end %>
    </li>
  <% end %>
</ul>