lib/chess_crunch_web/router.ex
defmodule ChessCrunchWeb.Router do
  use ChessCrunchWeb, :router

  import ChessCrunchWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ChessCrunchWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  scope "/", ChessCrunchWeb do
    pipe_through :browser
  end

  ## Authentication routes

  scope "/", ChessCrunchWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ChessCrunchWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", Redirector, to: "/cycles"
    resources "/cycles", CycleController, only: [:index, :create, :new, :show, :delete]
    live "/start_cycle/:id", CycleLive
    resources "/sets", SetController, only: [:index, :new, :create, :show, :delete]
    resources "/positions", PositionController, only: [:new, :create, :delete]
    live "/positions/:id/edit", EditPositionLive
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ChessCrunchWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChessCrunchWeb.Telemetry
    end
  end
end

lib/chess_crunch_web/views/layout_view.ex
defmodule ChessCrunchWeb.LayoutView do
  use ChessCrunchWeb, :view
end

lib/chess_crunch_web/templates/layout/_user_menu.html.eex
<%= if @current_user do %>
  <div x-data="{ mobileMenuOpen: false }">
    <button @click="mobileMenuOpen = !mobileMenuOpen" class="inline-block md:hidden">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
      </svg>
    </button>
    <nav x-show="mobileMenuOpen" class="flex absolute top-14 left-0 shadow-md rounded-lg flex-col pt-2 pr-2 bg-gray-200 w-full md:flex md:rounded-none md:shadow-none md:relative md:top-0 md:space-x-6 md:w-auto md:bg-transparent md:flex-row md:pt-0 z-10"
      @click.outside="mobileMenuOpen = false">
      <%= link "Drills", to: Routes.cycle_path(@conn, :index), class: "pl-3 py-1" %>
      <%= link "Position Sets", to: Routes.set_path(@conn, :index), class: "pl-3 py-1" %>
      <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "pl-3 py-1" %>
      <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "pl-3 py-1" %>
    </nav>
  </div>
<% end %>

lib/chess_crunch_web/templates/layout/app.html.eex
<main role="main">
  <p class="alert alert-info text-center" role="alert"><%= get_flash(@conn, :info) %></p>
  <%= @inner_content %>
</main>